name: kafka-nifi-monitoring

services:
  kafka:
    build:
      context: ./kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "[::1]:8080:8080"  # Kafka Web UI
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  nifi:
    build:
      context: ./nifi
    ports:
      - "[::1]:8443:8443"  # NiFi Web UI

  hdfs:
    build:
      context: ./hdfs

  hue:
    build:
      context: ./hue
    ports:
      - "[::1]:8888:8888"  # Hue Web UI
